{{/*
Copyright (c) 2026 BITKAIO LLC. All rights reserved.
*/}}
{{- if .Values.chromium.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palena.fullname" . }}-chromium
  labels:
    {{- include "palena.labels" . | nindent 4 }}
    app.kubernetes.io/component: chromium
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "palena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chromium
  template:
    metadata:
      labels:
        {{- include "palena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chromium
    spec:
      containers:
        - name: chromium
          image: "{{ .Values.chromium.image.repository }}:{{ .Values.chromium.image.tag }}"
          imagePullPolicy: {{ .Values.chromium.image.pullPolicy }}
          ports:
            - name: ws
              containerPort: {{ .Values.chromium.service.port }}
              protocol: TCP
          env:
            - name: MAX_CONCURRENT_SESSIONS
              value: {{ .Values.chromium.maxConcurrentSessions | quote }}
            - name: TIMEOUT
              value: "30000"
          resources:
            {{- toYaml .Values.chromium.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palena.fullname" . }}-chromium
  labels:
    {{- include "palena.labels" . | nindent 4 }}
    app.kubernetes.io/component: chromium
spec:
  type: {{ .Values.chromium.service.type }}
  ports:
    - port: {{ .Values.chromium.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "palena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chromium
{{- end }}