# Copyright (c) 2026 bitkaio LLC. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE for details.

FROM python:3.11-slim

WORKDIR /app

COPY flashrank-requirements.txt .
RUN pip install --no-cache-dir --require-hashes=false -r flashrank-requirements.txt

COPY flashrank_server.py .

ENV PORT=8080
EXPOSE 8080

CMD ["python", "flashrank_server.py"]